### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by meichuanneiku** [zhangmxxx/XrayUI#1]
项目工程中的XrayCore.xcframework和Greeter.xcframework包，请问是否能开源呢？如果可以的话，发邮箱xinyangme00@163.com,十分感谢

**Comment by zhangmxxx** [comment]
项目工程中的XrayCore.xcframework编译方法见[issue].(https://github.com/v2fly/v2ray-core/issues/1702)

**Comment by zhangmxxx** [comment]
项目中的XrayCore.xcframework编译方法见[issue](https://github.com/v2fly/v2ray-core/issues/1702).

**Comment by zhangmxxx** [comment]
项目中的XrayCore.xcframework: [google-drive-link](https://drive.google.com/file/d/1kgZplp4jIeJ1PMiBDNtXLGQvYIdeqWO_/view?usp=drive_link)
项目中的Greeter.xcframework: [google-drive-link](https://drive.google.com/file/d/1rwGcpl44FmbjKB7sG-sZKfJz1rVYU8XE/view?usp=drive_link)
