### ISSUE TITLE
少了两个.xcframework

### ISSUE THREAD

**Issue by Bamboo742** [zhangmxxx/XrayUI#4]
XRocket
There is no XCFramework found at '/Users/a0000/Greeter/greeter/Greeter.xcframework'.

There is no XCFramework found at '/Users/a0000/XrayCore.xcframework'.

/Users/a0000/code/XrayUI/XRocket/SwiftPrinter.swift
/Users/a0000/code/XrayUI/XRocket/SwiftPrinter.swift:9:8 No such module 'Greeter'

**Comment by zhangmxxx** [comment]
可以通过Google Drive获取：[XrayCore.xcframework.zip](https://drive.google.com/file/d/1kgZplp4jIeJ1PMiBDNtXLGQvYIdeqWO_/view?usp=drive_link)，[Greeter.xcframework.zip](https://drive.google.com/file/d/1rwGcpl44FmbjKB7sG-sZKfJz1rVYU8XE/view?usp=drive_link)

**Comment by YangCheng0121** [comment]
谢谢，我也在集成，不过是写Flutter插件为此学了一波Swfit，参考你的思路。给点了一个star
