### ISSUE TITLE
xray-core打包.xcframework

### ISSUE THREAD

**Issue by jctrace** [zhangmxxx/XrayUI#5]
你好，方便加下联系方式嘛，请教下如何将xray-core源码打包成 .xcframework

**Comment by zhangmxxx** [comment]
这个[issue](https://github.com/zhangmxxx/XrayUI/issues/4)里放了Google Drive链接。

**Comment by jctrace** [comment]
想自己通过gomobile将xray-core源码打包成 .xcframework引入到Xcode里面的，试了好几天都没能成功编译打包，方便加下联系方式请教下嘛

**Comment by zhangmxxx** [comment]
这个[issue](https://github.com/v2fly/v2ray-core/issues/1702#issuecomment-1951382816)里有我打包xcframework的做法.

**Comment by jctrace** [comment]
按照上面的做法还是报错，以下是我的操作步骤

1、下载 go1.23.2.darwin-arm64.tar.gz

2、mv go1.23.2.darwin-arm64.tar.gz /usr/local/

3、解压 sudo tar -zxvf go1.23.2.darwin-arm64.tar.gz

4、配置GO环境变量 vim ~/.zshrc 

export GOROOT=/usr/local/go
export GOPATH=/Users/lmm/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN:$GOROOT/bin

5、生效 source ~/.zshrc

6、查看GO版本 go version     

go version go1.23.2 darwin/arm64

7、go install golang.org/x/mobile/cmd/gomobile@latest

8、go init

9、执行完上面命令，在GOPATH目录下多了2个文件夹 bin、pkg，bin文件夹里面有2个执行文件 gobind、gomobile 

10、下载xray-core源码版本v1.8.24

11、cd xray-core 

12、执行命令 ：sudo gomobile bind -v -target=ios -o v2Ray.xcframework -ldflags='-s -w' ./

报错：

no exported names in the package "."
no exported names in the package "."
unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind: no Go package in golang.org/x/mobile/bind
no exported names in the package "."
unable to import bind: no Go package in golang.org/x/mobile/bind
no exported names in the package "."
no exported names in the package "."
no exported names in the package "."
no exported names in the package "."
no exported names in the package "."
unable to import bind/objc: no Go package in golang.org/x/mobile/bind/objc
unable to import bind/objc: no Go package in golang.org/x/mobile/bind/objc
gomobile: /Users/lmm/go/bin/gobind -lang=go,objc -outdir=/tmp/gomobile-work-1606136668/iossimulator -tags=ios . failed: exit status 1

13、添加了 entry.go 

entry.go文件内容：

package entry

func RunMain(){
main()
}

执行命令： sudo gomobile bind -v -target=ios -o v2Ray.xcframework -ldflags='-s -w' ./

报错：

unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind: no Go package in golang.org/x/mobile/bind
unable to import bind/objc: no Go package in golang.org/x/mobile/bind/objc
unable to import bind/objc: no Go package in golang.org/x/mobile/bind/objc
gomobile: /Users/lmm/go/bin/gobind -lang=go,objc -outdir=/tmp/gomobile-work-3830825183/iossimulator -tags=ios github.com/xtls/xray-core failed: exit status 1

**Comment by zhangmxxx** [comment]
我对go非常不熟悉，甚至现在已经记不清我自己描述的步骤了。所以实在无力帮助。

**Comment by jctrace** [comment]
嗯嗯感谢支持
